name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Check if .editorconfig exists
        uses: andstor/file-existence-action@v1
        with:
          files: ".editorconfig"
          allow_failure: true

      - name: EditorConfig validation
        uses: snow-actions/eclint@v1.0.1

      - name: Ensure node_modules is ignored by Git
        uses: dkershner6/gitignore-parser@v1
        with:
          must_deny: "node_modules/"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: Install modules
        run: pnpm i --frozen-lockfile

      - name: prettier
        run: pnpm prettier:check

      - name: ESLint validation
        run: pnpm eslint
